# This Docker Compose file excludes the local Telegram Bot API server.
# Use this configuration if you don't need to run your own local instance
# of the Telegram Bot API server.

version: "3.8"

services:

  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    env_file:
      - .env
    command: ngrok http telegram-bot:8000
    ports:
      - "4040:4040"

  telegram-bot:
    build: .
    depends_on:
      - ngrok
    command: >
      sh -c "pipenv run uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
